Repository TitTolkachev/tsu-schedule, pull requests merged in 2023-03, with the labels that each got.

#1 Страница авторизации
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/constants.ts
  src/app/models/jwt.spec.ts
  src/app/models/jwt.ts
  src/app/models/token.spec.ts
  src/app/models/token.ts
  src/app/pages/signin/signin.component.css
  src/app/pages/signin/signin.component.html
  src/app/pages/signin/signin.component.ts
  src/app/pages/signout/signout.component.html
  src/app/pages/signout/signout.component.spec.ts
  src/app/pages/signout/signout.component.ts
  src/app/routing-guard.ts
  src/app/services/auth.service.spec.ts
  src/app/services/auth.service.ts
  src/app/services/token-interceptor.service.spec.ts
  src/app/services/token-interceptor.service.ts
  src/index.html
Labels: enhancement

#5 Feature/admin pages
  src/app/app.module.ts
  src/app/pages/admin/audiences/audience-element/audience-element.component.css
  src/app/pages/admin/audiences/audience-element/audience-element.component.html
  src/app/pages/admin/audiences/audiences-page/audiences-page.component.css
  src/app/pages/admin/audiences/audiences-page/audiences-page.component.html
  src/app/pages/admin/audiences/audiences-page/audiences-page.component.ts
  src/app/pages/admin/audiences/search-audience/search-audience.pipe.spec.ts
  src/app/pages/admin/audiences/search-audience/search-audience.pipe.ts
  src/app/pages/admin/groups/group-element/group-element.component.css
  src/app/pages/admin/groups/group-element/group-element.component.html
  src/app/pages/admin/groups/groups-page/groups-page.component.css
  src/app/pages/admin/groups/groups-page/groups-page.component.html
  src/app/pages/admin/groups/groups-page/groups-page.component.ts
  src/app/pages/admin/groups/search-groups/search-groups.pipe.spec.ts
  src/app/pages/admin/groups/search-groups/search-groups.pipe.ts
  src/app/pages/admin/subjects/search-subjects/search-subjects.pipe.spec.ts
  src/app/pages/admin/subjects/search-subjects/search-subjects.pipe.ts
  src/app/pages/admin/subjects/subject-element/subject-element.component.css
  src/app/pages/admin/subjects/subject-element/subject-element.component.html
  src/app/pages/admin/subjects/subjects-page/subjects-page.component.css
  src/app/pages/admin/subjects/subjects-page/subjects-page.component.html
  src/app/pages/admin/subjects/subjects-page/subjects-page.component.ts
  src/app/pages/admin/teachers/search-teacher/search-teacher.pipe.spec.ts
  src/app/pages/admin/teachers/search-teacher/search-teacher.pipe.ts
  src/app/pages/admin/teachers/teacher-element/teacher-element.component.css
  src/app/pages/admin/teachers/teacher-element/teacher-element.component.html
  src/app/pages/admin/teachers/teachers-page/teachers-page.component.css
  src/app/pages/admin/teachers/teachers-page/teachers-page.component.html
  src/app/pages/admin/teachers/teachers-page/teachers-page.component.ts
  src/assets/img/delete.svg
  src/assets/img/edit.svg
Labels: enhancement

#6 Исправление ошибок и багов в админ-панели
  src/app/app.module.ts
  src/app/models/audience.ts
  src/app/models/group.ts
  src/app/models/jwt.ts
  src/app/models/subject.ts
  src/app/models/teacher.ts
  src/app/models/token.ts
  src/app/pages/admin/audiences/audiences-page/audiences-page.component.ts
  src/app/pages/admin/groups/groups-page/groups-page.component.ts
  src/app/pages/admin/subjects/subjects-page/subjects-page.component.ts
  src/app/pages/admin/teachers/teacher-element/teacher-element.component.html
  src/app/pages/admin/teachers/teachers-page/teachers-page.component.html
  src/app/pages/admin/teachers/teachers-page/teachers-page.component.ts
  src/app/services/mock/audience-mock.service.ts
  src/app/services/mock/group-mock.service.ts
  src/app/services/mock/subject-mock.service.ts
  src/app/services/mock/teacher-mock.service.ts
Labels: bug, enhancement

#10 Сверстана страница с запросами
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/reject/reject.component.css
  src/app/components/reject/reject.component.html
  src/app/components/reject/reject.component.spec.ts
  src/app/components/reject/reject.component.ts
  src/app/pages/admin/requests/request-element/request.component.css
  src/app/pages/admin/requests/request-element/request.component.html
  src/app/pages/admin/requests/request-element/request.component.spec.ts
  src/app/pages/admin/requests/request-element/request.component.ts
  src/app/pages/admin/requests/requests-page/requests-page.component.css
  src/app/pages/admin/requests/requests-page/requests-page.component.html
  src/app/pages/admin/requests/requests-page/requests-page.component.spec.ts
  src/app/pages/admin/requests/requests-page/requests-page.component.ts
  src/app/pages/admin/requests/search-request/search-request.pipe.spec.ts
  src/app/pages/admin/requests/search-request/search-request.pipe.ts
  src/assets/img/confirm.svg
  src/assets/img/reject.svg
Labels: enhancement

#11 В поле "пароль" всегда видимые вводимые значения
  src/app/pages/admin/users/users-modal/users-modal.component.html
Labels: bug, enhancement

#13 Связка компонента админ-панели запросов с бекендом
  src/app/app.module.ts
  src/app/components/reject/reject.component.html
  src/app/environment.prod.ts
  src/app/environment.ts
  src/app/errors.ts
  src/app/models/account.ts
  src/app/models/group-request.ts
  src/app/models/registration-request.ts
  src/app/pages/admin/requests/request-element/request.component.html
  src/app/pages/admin/requests/request-element/request.component.ts
  src/app/pages/admin/requests/requests-page/requests-page.component.html
  src/app/pages/admin/requests/requests-page/requests-page.component.ts
  src/app/pages/admin/teachers/teachers-page/teachers-page.component.ts
  src/app/pages/admin/users/user-element/user-element.component.html
  src/app/pages/admin/users/user-element/user-element.component.ts
  src/app/pages/admin/users/users-modal/users-modal.component.html
  src/app/pages/admin/users/users-modal/users-modal.component.ts
  src/app/pages/admin/users/users-page/users-page.component.html
  src/app/pages/admin/users/users-page/users-page.component.ts
  src/app/pages/signin/signin.component.html
  src/app/pages/signin/signin.component.ts
  src/app/services/dao/request.service.spec.ts
  src/app/services/dao/request.service.ts
  src/app/services/dao/user.service.spec.ts
  src/app/services/dao/user.service.ts
  src/app/services/i-request.service.ts
  src/app/services/i-user.service.ts
  src/app/services/mock/request-mock.service.spec.ts
  src/app/services/mock/request-mock.service.ts
  src/app/services/mock/user-mock.service.spec.ts
  src/app/services/mock/user-mock.service.ts
Labels: enhancement

#15 Исправлен баг с поиском на страницах
  src/app/models/audience.ts
  src/app/pages/admin/audiences/audience-element/audience-element.component.html
  src/app/pages/admin/audiences/audience-modal/audience-modal.component.ts
  src/app/pages/admin/audiences/search-audience/search-audience.pipe.ts
  src/app/pages/admin/teachers/search-teacher/search-teacher.pipe.ts
  src/app/services/dao/audience.service.ts
  src/app/services/mock/audience-mock.service.ts
Labels: bug

#16 Исправление авторизации и логаута
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/pages/main/main.component.spec.ts
  src/app/pages/main/main.component.ts
  src/app/pages/signin/signin.component.ts
  src/app/pages/signout/signout.component.html
  src/app/pages/signout/signout.component.ts
  src/app/services/auth.service.ts
  src/app/services/token-interceptor.service.ts
Labels: bug, enhancement

#12 Связка компонента админ-панели пользователей с бекендом
  src/app/errors.ts
  src/app/pages/admin/users/user-element/user-element.component.html
  src/app/pages/admin/users/user-element/user-element.component.ts
  src/app/pages/admin/users/users-modal/users-modal.component.html
  src/app/pages/admin/users/users-modal/users-modal.component.ts
  src/app/pages/admin/users/users-page/users-page.component.html
  src/app/pages/admin/users/users-page/users-page.component.ts
  src/app/services/dao/user.service.ts
  src/app/services/i-user.service.ts
  src/app/services/mock/user-mock.service.ts
Labels: enhancement

#17 Исправлено отображение отчества
  src/app/pages/admin/requests/request-element/request.component.ts
  src/app/pages/admin/teachers/teacher-element/teacher-element.component.html
  src/app/pages/admin/teachers/teachers-page/teachers-page.component.ts
  src/app/pages/admin/users/user-element/user-element.component.html
Labels: bug

#19 Исправлен баг с добавлением пользователя
  src/app/services/dao/user.service.ts
Labels: bug

#20 Исправлен баг с удалением пользователя
  src/app/services/dao/user.service.ts
Labels: bug

#21 Исправлен баг с отклонением и принятием запросов
  src/app/pages/admin/requests/requests-page/requests-page.component.ts
Labels: bug

#23 Исправлена верстка
  src/app/pages/admin/users/users-modal/users-modal.component.css
  src/app/pages/admin/users/users-modal/users-modal.component.html
Labels: bug

#22 Исправлена верстка и убрана кнопка удаления для аккаунтов админа и составителя
  src/app/pages/admin/users/user-element/user-element.component.css
  src/app/pages/admin/users/user-element/user-element.component.html
  src/app/pages/admin/users/users-modal/users-modal.component.css
  src/assets/img/admin.svg
Labels: bug
